apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernetes-controller
  namespace: supernetes
spec:
  replicas: 1 # Multiple replicas not yet supported
  selector:
    matchLabels:
      app: supernetes
  template:
    metadata:
      labels:
        app: supernetes
    spec:
      containers:
        - name: controller
          image: ghcr.io/supernetes/controller
          args:
            - --config
            - /config/config.yaml
          env:
          - name: SUPERNETES_CONTROLLER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SUPERNETES_CONTROLLER_SERVICEACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: SUPERNETES_CONTROLLER_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            # The configuration secret must be provided by
            # the user, use the `config` tool to generate it
            secretName: supernetes-config
        - name: data
          emptyDir: {}
      serviceAccountName: supernetes
