apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: supernetes
  namespace: supernetes
spec:
  parentRefs:
    - name: supernetes
      sectionName: grpc
  rules:
    - backendRefs:
        - name: supernetes
          port: 40404
