apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest/controller.yaml
  - manifest/namespace.yaml
  - manifest/rbac.yaml
  - manifest/route.yaml
  - manifest/service.yaml
