// SPDX-License-Identifier: MPL-2.0
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package cmd

import (
	"github.com/lithammer/dedent"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/supernetes/supernetes/common/pkg/log"
)

var logLevel string

func NewRootCommand() *cobra.Command {
	root := &cobra.Command{
		Use:   "agent",
		Short: "Supernetes HPC agent",
		Long: dedent.Dedent(`
			This is the Supernetes agent, intended to be executed on a login node or as a
			system process in an HPC environment. The agent takes in the ` + "`agent.yaml`" + `
			configuration generated by the ` + "`config generate`" + ` Supernetes tool. The agent
			interfaces with the local HPC runtime (Slurm) and requires outbound connectivity
			to a Supernetes controller running in the cloud (Kubernetes cluster).

			Supernetes requires an HPC container runtime to be present for deploying jobs.
			Currently, the agent supports Apptainer and Singularity CE.
		`),
		PersistentPreRun: func(cmd *cobra.Command, args []string) {
			log.Init(logLevel)
		},
	}

	addGlobalFlags(root.PersistentFlags())
	root.AddCommand(NewCmdRun())
	root.AddCommand(NewCmdDispatch())
	return root
}

func addGlobalFlags(fs *pflag.FlagSet) {
	fs.StringVarP(&logLevel, "log-level", "l", "info", "zerolog log level")
}
