on:
  pull_request:
  push:
    branches:
      - master

name: Check
jobs:
  conform:
    name: Conformance
    runs-on: ubuntu-24.04
    container:
      image: golang:1
      options: --user 1001 # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
    steps:
      - name: Check out sources
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get date
        id: get-date
        run: echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - name: Cache Golang resources
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: conform-${{ runner.arch }}-${{ steps.get-date.outputs.date }}
          restore-keys: conform-${{ runner.arch }}
      - name: Fetch master branch for reference
        # The main branch detection of siderolabs/conform relies on the branch tracking the "origin" remote, see
        # https://github.com/siderolabs/conform/blob/2feadaa74eef93dd35f303582f2e82afa62a119d/cmd/conform/enforce.go#L74
        run: git checkout master && git checkout -
        if: github.ref_name != 'master'
      - name: Install siderolabs/conform
        run: go install github.com/siderolabs/conform/cmd/conform@latest
      - name: Run siderolabs/conform
        run: conform enforce
  tidy:
    name: Module Tidiness
    runs-on: ubuntu-24.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v5
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
          fetch-depth: 0
          filter: tree:0
      - name: Set up runtime
        uses: ./.github/actions/runtime
      - name: Run make tidy
        run: make tidy
      - name: Check changed files
        id: check-changed-files
        uses: tj-actions/verify-changed-files@v20
        with:
          read-gitignore: true
      - name: List changed files
        if: steps.check-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.check-changed-files.outputs.changed_files }}
        run: |
          cat <<- EOF
            Unexpected file changes:
            $CHANGED_FILES

            Please run \`make tidy\` and try again.
          EOF
          exit 1
  # It's 2024 and https://github.com/golangci/golangci-lint/issues/828 has still not been resolved
  resolve-modules:
    name: Resolve Modules
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v5
      - name: Discover modules
        id: set-matrix
        run: |
          PATHS=$(find . -type f -name go.mod -printf '{"workdir":"%h"},')
          echo "matrix={\"include\":[${PATHS%?}]}" >> "$GITHUB_OUTPUT"
  golangci:
    name: Linting
    needs: resolve-modules
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Check out sources
        uses: actions/checkout@v5
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
          fetch-depth: 0
          filter: tree:0
      - name: Set up runtime
        uses: ./.github/actions/runtime
      - name: Compile Protobuf artifacts
        run: make proto
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
          version: latest
          working-directory: ${{ matrix.workdir }}
