on:
  pull_request:
    types:
      - closed # PR closed (whether merged or not)

name: Cleanup
jobs:
  cleanup:
    name: Configuration
    runs-on: ubuntu-24.04
    if: github.event.ref_type != 'tag' # Ignore tags for now
    env:
      BRANCH_NAME: ${{ format('pull-{0}', github.event.number) }}
    steps:
      - name: Check out deployment repository
        uses: actions/checkout@v5
        with:
          repository: supernetes/deploy
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Prune stale deploy branch
        run: |
          git push -d origin "$BRANCH_NAME" ||:
